Retrofit
Vladi71/nMedia pull request #4
Opened 2021-05-02 19:02 UTC by Vladi71

2021-05-03 13:29 UTC, maks1596 requested changes
`PostViewModel` конфликтует и не разрешит завершить PR. Разрешите конфликт локально, чтобы в PR отображались только зелёные галочки

2021-05-03 13:29 UTC, maks1596 commented on app/src/main/java/ru/netology/api/PostsApiService.kt
> +private val client = OkHttpClient.Builder()
`client` и `retrofit` cоздадутся сразу при старте программы, чем замедлят её запуск. В действительности же они понадобятся только при создании `retrofitService`

2021-05-03 13:29 UTC, maks1596 commented on local.properties
> +## This file must *NOT* be checked into Version Control Systems,
Пропустили этот файлик для системы контроля версий Git 😊

2021-05-03 13:29 UTC, maks1596 commented on app/src/main/java/ru/netology/api/PostsApiService.kt
> +    val retrofitService: PostsApiService by lazy {
Органичнее смотрелась бы запись `PostsApiService.getInstance()` или даже `PostsApiService()` - не надо запоминать имя ещё одного класса.
P.S.: Оба варианта реализуются через `companion object`.
P.P.S.: Второй вариант можете сейчас для себя найти как реализовать и применить в данном академическом проекте, но, пожалуйста, не используйте на реальных проектах. Это плохой код, который разрывает сознание в попытках осознать "как у интерфейса может быть конструктор?!"

2021-05-03 13:29 UTC, maks1596 commented on app/src/main/java/ru/netology/repository/PostRepository.kt
> +    interface Callback<T> {
1. По-моему, `GetAllCallback` и `GetPostCallback` можно заменить на `Callback<List<Post>>` и `Callback<Post>`, соответственно.
2. Вместо `Callback` можно спокойно использовать `kotlin`-овский `Result`

2021-05-03 13:29 UTC, maks1596 commented on app/src/main/java/ru/netology/repository/PostRepositoryImpl.kt
> +                TODO("Not yet implemented")
Приложение упадёт с не очень-то понятной ошибкой. Лучше реализовать

2021-05-03 13:29 UTC, maks1596 commented on app/src/main/java/ru/netology/repository/PostRepositoryImpl.kt
> +                        ?: throw java.lang.RuntimeException("body is null"))
Не надо `java.lang.RuntimeException`. Лучше положиться на kotlin и выбросить просто `RuntimeException`

2021-05-03 13:29 UTC, maks1596 commented on app/src/main/java/ru/netology/repository/PostRepositoryImpl.kt
> +            override fun onResponse(call: Call<List<Post>>, response: Response<List<Post>>) {
Посмотрите на код всех Ваших обработчиков `Callback`, которые вы предоставляете в метод `enqueue`. Единственное отличие между ними - тип: `Post`, `Unit` или `List<Post>`. Используйте generics и уменьшите количество повторяющегося кода

2021-05-03 13:29 UTC, maks1596 commented on app/src/main/java/ru/netology/repository/PostRepositoryImpl.kt
> +                callback.onSuccess(response.body() ?: throw RuntimeException("body is null"))
Тип ожидаемого результата - `Unit`. То есть `Ничего`. Что Вы тогда ожидаете получить в теле ответа `response.body()`? Высока вероятность, что приложение здесь будет падать, потому что тело ответа - `null`.

2021-05-03 20:17 UTC, Vladi71 commented on app/src/main/java/ru/netology/api/PostsApiService.kt
> +    val retrofitService: PostsApiService by lazy {
Я не совсем понял как это реализовать

2021-05-04 21:35 UTC, maks1596 requested changes

2021-05-04 21:35 UTC, maks1596 commented on app/src/main/java/ru/netology/api/PostsApiService.kt
> +    val retrofitService: PostsApiService by lazy {
Приоткрою же завесу тайны, но потом обязательно всё самостоятельно прочитайте в документации
```kotlin
// 1. Ваш вариант
object PostApi {
    val retrofitService by lazy {
        // формируем сервис
    }
}


interface Service {

    // 2. PostApi можно без проблем занести внутрь интерфейса сервиса 
    // и дать более говорящее название
    object Factory {
        val instance by lazy {
            // формируем сервис
        }
    }
    
    // 3. Преимущество companion object в том, что при вызове его методов и свойств
    // можно опускать его имя... Собственно, имя для companion object можно впринципе не задавать
    companion object /*Factory - можно опустить*/ {
        
        // Всё ещё Ваш вариант
        val instance by lazy {
            // формируем сервис
        }

        // Предложенные мной варианты
        fun getInstance() = instance
        operator fun invoke() = instance
    }
}

// Ваш вариант
val service = PostApi.retrofitService

// Занесли PostApi внутрь Service, чтобы не потерять и переименовали в Factory
val service = Service.Factory.instance

// Поменяли object Factory на companion object
// Для companion object автоматически генерируется имя Companion, если Вы его не задали вручную.
val service = Service.Companion.instance

// Имя companion object можно опустить 
val service = Service.instance

// Варианты, про которые я говорил
val service = Service.getInstance()
val service = Service()
```

2021-05-05 19:42 UTC, maks1596 requested changes

2021-05-05 19:42 UTC, maks1596 commented on app/src/main/java/ru/netology/repository/PostRepositoryImpl.kt
> +            override fun onFailure(call: Call<List<Post>>, t: Throwable) {
Опишите, пожалуйста, свою реализацию. Что происходит в `onFailure`?

2021-05-10 21:22 UTC, maks1596 requested changes

2021-05-10 21:22 UTC, maks1596 commented on app/src/main/java/ru/netology/Activity/PostFragment.kt
> +            binding.publishedTv.text = Utils.convertDate()
По-моему было правильно. У Вас сейчас в поле `publishedTv` будет всегда отображаться текущая дата - такова реализация `Utils.convertDate()`.

2021-05-10 21:22 UTC, maks1596 commented on app/src/main/java/ru/netology/Utils.kt
> +        fun convertDate(): String {
Название функции запутывает. Ей больше подошло бы название, содержащее `now`, потому что эта функция всегда возвращает текущее время в текстовом виде

2021-05-13 16:30 UTC, merged